### ISSUE TITLE
Sec-WebSocket-Protocol problem

### ISSUE THREAD

**Issue by xralphack** [fanout/express-grip#1]
I want to use Sec-WebSocket-Protocol on the web.

`const ws = new WebSocket("wss://...", "my-protocol");`

 the error message is 

failed: Error during WebSocket handshake: Sent non-empty 'Sec-WebSocket-Protocol' header but no response was received

However, I used the same code on react-native, everything works fine.

Any suggestion?

**Comment by jkarneges** [comment]
Are you responding with Sec-WebSocket-Protocol from the server side, to acknowledge the selection?

If not, that's probably the issue, and maybe react-native is less picky about this.

**Comment by xralphack** [comment]
How can I acknowledge the selection?
I use Sec-WebSocket-Protocol to pass the jwt to my server.

**Comment by jkarneges** [comment]
Respond with the same header from the server:

```js
res.set('Sec-WebSocket-Protocol', 'my-protocol');
```

**Comment by xralphack** [comment]
I will try this.

**Comment by xralphack** [comment]
It works now~ thx for your help

**Comment by jkarneges** [comment]
Great!
